MINERALS = [{'name': 'Quartz',
  'category': 'Silicate',
  'description': 'Minéral le plus courant de la croûte continentale, souvent incolore à blanc, à éclat vitreux.',
  'chemicalFormula': 'SiO₂',
  'physicalCharacteristics': 'Dureté 7, pas de clivage, cassure conchoïdale, cristaux prismatiques terminés en pyramide.',
  'formationEnvironment': 'Roches magmatiques acides, roches métamorphiques, veines hydrothermales et sédiments détritiques.',
  'commonUses': 'Verre, électronique, abrasifs, construction.',
  'confirmationTests': "Il raye le verre et l'acier, ne se clive pas et ne réagit pas à l'acide.",
  'safetyWarning': "Éviter l'inhalation de poussières de silice.",
  'luster': 'vitreous',
  'color': 'transparent,white,gray,pink,brown,purple',
  'streak': 'white,none',
  'hardness': 'very-hard',
  'cleavage': 'none',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'prismatic,massive,granular'},
 {'name': 'Calcite',
  'category': 'Carbonate',
  'description': 'Carbonate de calcium très fréquent dans les calcaires, les marbres et les veines hydrothermales.',
  'chemicalFormula': 'CaCO₃',
  'physicalCharacteristics': "Dureté 3, clivage rhomboédrique parfait (3 directions non perpendiculaires), effervescence à l'acide dilué "
                             'froid.',
  'formationEnvironment': 'Roches sédimentaires carbonatées, marbres, veines hydrothermales et spéléothèmes.',
  'commonUses': 'Ciment, chaux, amendement agricole, charge industrielle.',
  'confirmationTests': 'Une réaction franche à un test acide encadré en laboratoire ; elle est rayée par une pièce de cuivre.',
  'safetyWarning': 'Acide corrosif : gants et lunettes obligatoires.',
  'luster': 'vitreous,pearly',
  'color': 'white,transparent,yellow,gray,pink,brown',
  'streak': 'white',
  'hardness': 'medium',
  'cleavage': 'three-directions',
  'magnetic': 'no',
  'acidReaction': 'strong',
  'crystalHabit': 'massive,granular,prismatic'},
 {'name': 'Dolomite',
  'category': 'Carbonate',
  'description': "Carbonate double de calcium et de magnésium, proche de la calcite mais moins réactif à l'acide.",
  'chemicalFormula': 'CaMg(CO₃)₂',
  'physicalCharacteristics': 'Dureté 3,5 à 4, cristaux rhomboédriques souvent courbes, clivage rhomboédrique.',
  'formationEnvironment': 'Dolomies sédimentaires, transformation des calcaires, veines hydrothermales.',
  'commonUses': 'Pierre de construction, fondant en métallurgie, source de magnésium.',
  'confirmationTests': "Pas d'effervescence nette sur un bloc à froid ; elle n'apparaît que sur la poudre grattée.",
  'safetyWarning': 'Acide corrosif : gants et lunettes obligatoires.',
  'luster': 'vitreous,pearly',
  'color': 'white,pink,gray,brown',
  'streak': 'white',
  'hardness': 'medium',
  'cleavage': 'three-directions',
  'magnetic': 'no',
  'acidReaction': 'weak',
  'crystalHabit': 'massive,granular'},
 {'name': 'Pyrite',
  'category': 'Sulfure',
  'description': 'Sulfure de fer à éclat métallique, jaune laiton, souvent en cristaux cubiques striés.',
  'chemicalFormula': 'FeS₂',
  'physicalCharacteristics': 'Dureté 6 à 6,5, éclat métallique, cubes ou pyritoèdres, trace noire verdâtre.',
  'formationEnvironment': 'Gisements hydrothermaux, roches sédimentaires et métamorphiques.',
  'commonUses': 'Source de soufre, minéral associé aux gîtes métalliques.',
  'confirmationTests': "Elle fait des étincelles contre l'acier, ne se raye pas au couteau et laisse une trace noire.",
  'safetyWarning': "Ne pas inhaler les poussières ; l'altération produit de l'acide sulfurique.",
  'luster': 'metallic',
  'color': 'yellow',
  'streak': 'black',
  'hardness': 'hard',
  'cleavage': 'none',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'cubic,massive,granular'},
 {'name': 'Chalcopyrite',
  'category': 'Sulfure',
  'description': 'Sulfure de cuivre et de fer jaune laiton, principal minerai de cuivre.',
  'chemicalFormula': 'CuFeS₂',
  'physicalCharacteristics': 'Dureté 3,5 à 4, plus tendre et plus jaune que la pyrite, irisations fréquentes, trace noire verdâtre.',
  'formationEnvironment': 'Gisements hydrothermaux, porphyres cuprifères et amas sulfurés volcanogènes.',
  'commonUses': 'Principal minerai de cuivre.',
  'confirmationTests': 'Elle se raye au couteau (contrairement à la pyrite) et laisse une trace noire verdâtre.',
  'safetyWarning': "Poussières et altération libèrent des métaux et de l'acide : gants et lavage des mains.",
  'luster': 'metallic',
  'color': 'yellow,other',
  'streak': 'black',
  'hardness': 'medium',
  'cleavage': 'none',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'massive,granular'},
 {'name': 'Magnétite',
  'category': 'Oxyde',
  'description': 'Oxyde de fer fortement magnétique, noir à éclat métallique.',
  'chemicalFormula': 'Fe₃O₄',
  'physicalCharacteristics': 'Dureté 5,5 à 6,5, dense, noir, attiré nettement par un aimant.',
  'formationEnvironment': 'Roches magmatiques, métamorphiques et gisements de fer.',
  'commonUses': 'Minerai de fer.',
  'confirmationTests': "Un petit aimant l'attire fortement ; la trace est noire.",
  'safetyWarning': "Éviter d'inhaler les poussières.",
  'luster': 'metallic',
  'color': 'black,gray',
  'streak': 'black',
  'hardness': 'hard',
  'cleavage': 'none',
  'magnetic': 'yes',
  'acidReaction': 'none',
  'crystalHabit': 'granular,massive'},
 {'name': 'Hématite',
  'category': 'Oxyde',
  'description': 'Oxyde de fer gris métallique à rouge-brun terreux, à trace rouge caractéristique.',
  'chemicalFormula': 'Fe₂O₃',
  'physicalCharacteristics': "Dureté 5 à 6,5 (moins pour les variétés terreuses), trace rouge-brun même quand l'échantillon est gris.",
  'formationEnvironment': 'Roches sédimentaires (fer rubané), magmatiques et métamorphiques.',
  'commonUses': 'Minerai de fer, pigment.',
  'confirmationTests': "La trace rouge-brun est le test décisif ; elle n'est pas attirée par l'aimant.",
  'safetyWarning': "Éviter d'inhaler les poussières.",
  'luster': 'metallic,dull',
  'color': 'gray,red,brown,black',
  'streak': 'red-brown',
  'hardness': 'hard,medium',
  'cleavage': 'none',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'botryoidal,massive,granular'},
 {'name': 'Limonite (goethite)',
  'category': 'Oxyde-hydroxyde',
  'description': "Mélange d'oxydes de fer hydratés brun-jaune, produit d'altération des roches riches en fer.",
  'chemicalFormula': 'FeO(OH)·nH₂O',
  'physicalCharacteristics': 'Aspect terreux ou mamelonné, dureté variable, trace brun-jaune.',
  'formationEnvironment': 'Altération supergène (chapeau de fer) des roches et des gîtes riches en fer.',
  'commonUses': 'Minerai de fer, pigments ocres.',
  'confirmationTests': "Trace brun-jaune (ocre) ; elle n'est pas attirée par l'aimant ; aspect terreux.",
  'safetyWarning': "Éviter d'inhaler les poussières.",
  'luster': 'dull',
  'color': 'brown,yellow',
  'streak': 'brown,yellow',
  'hardness': 'medium,soft',
  'cleavage': 'none',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'massive,botryoidal,granular'},
 {'name': 'Halite',
  'category': 'Halogénure',
  'description': 'Sel gemme, incolore à blanc, à clivage cubique.',
  'chemicalFormula': 'NaCl',
  'physicalCharacteristics': 'Dureté 2,5, clivage en trois directions à angle droit, cristaux cubiques.',
  'formationEnvironment': 'Évaporites et bassins sédimentaires.',
  'commonUses': 'Sel alimentaire et usages industriels après traitement.',
  'confirmationTests': 'Observer le clivage cubique. Ne jamais goûter un échantillon de terrain.',
  'safetyWarning': 'Ne jamais goûter ni lécher les minéraux.',
  'luster': 'vitreous',
  'color': 'white,transparent,pink,gray,blue',
  'streak': 'white',
  'hardness': 'soft',
  'cleavage': 'three-directions',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'cubic,massive'},
 {'name': 'Gypse',
  'category': 'Sulfate',
  'description': 'Sulfate de calcium hydraté très tendre.',
  'chemicalFormula': 'CaSO₄·2H₂O',
  'physicalCharacteristics': "Dureté 2 : il se raye à l'ongle. Clivage parfait dans une direction, cristaux en fer de lance ou fibreux.",
  'formationEnvironment': 'Évaporites et dépôts sédimentaires.',
  'commonUses': 'Plâtre, ciment, matériaux de construction.',
  'confirmationTests': "Il se raye à l'ongle et ne réagit pas à l'acide.",
  'safetyWarning': "Éviter d'inhaler les poussières.",
  'luster': 'vitreous,pearly',
  'color': 'white,transparent,gray',
  'streak': 'white',
  'hardness': 'soft',
  'cleavage': 'one-direction',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'flaky,prismatic,massive'},
 {'name': 'Talc',
  'category': 'Silicate',
  'description': 'Silicate de magnésium hydraté, le minéral le plus tendre (Mohs 1), onctueux au toucher.',
  'chemicalFormula': 'Mg₃Si₄O₁₀(OH)₂',
  'physicalCharacteristics': 'Dureté 1, toucher savonneux, éclat nacré à gras, clivage parfait en feuillets.',
  'formationEnvironment': 'Métamorphisme de roches ultrabasiques et de carbonates magnésiens.',
  'commonUses': 'Cosmétiques, papier, peintures, céramique.',
  'confirmationTests': "Il se raye facilement à l'ongle, est savonneux au toucher et laisse une trace blanche.",
  'safetyWarning': "Éviter d'inhaler la poudre.",
  'luster': 'pearly,greasy',
  'color': 'white,green,gray',
  'streak': 'white',
  'hardness': 'soft',
  'cleavage': 'one-direction',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'massive,flaky'},
 {'name': 'Graphite',
  'category': 'Élément natif',
  'description': 'Carbone natif gris-noir, très tendre, qui marque le papier.',
  'chemicalFormula': 'C',
  'physicalCharacteristics': 'Dureté 1 à 2, gras au toucher, clivage parfait en feuillets, conducteur électrique.',
  'formationEnvironment': 'Roches métamorphiques (schistes, marbres) issues de matière organique.',
  'commonUses': 'Crayons, lubrifiants, électrodes, batteries.',
  'confirmationTests': "Il laisse une trace grise sur le papier, est onctueux et n'est pas magnétique.",
  'safetyWarning': "Poussières conductrices : éviter l'inhalation.",
  'luster': 'metallic,dull',
  'color': 'black,gray',
  'streak': 'black',
  'hardness': 'soft',
  'cleavage': 'one-direction',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'flaky,massive'},
 {'name': 'Mica',
  'category': 'Silicate',
  'description': 'Groupe de minéraux feuilletés à clivage parfait en lamelles flexibles (muscovite, biotite).',
  'chemicalFormula': 'Variable',
  'physicalCharacteristics': 'Feuillets flexibles et élastiques, éclat nacré, dureté 2 à 3.',
  'formationEnvironment': 'Roches magmatiques et métamorphiques.',
  'commonUses': 'Isolants électriques, charges minérales, cosmétiques.',
  'confirmationTests': "Détacher un feuillet avec la pointe d'un couteau : il est flexible et élastique.",
  'safetyWarning': "Éviter d'inhaler les poussières.",
  'luster': 'pearly,vitreous',
  'color': 'transparent,gray,brown,black,white,green',
  'streak': 'white',
  'hardness': 'soft,medium',
  'cleavage': 'one-direction',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'flaky'},
 {'name': 'Feldspath',
  'category': 'Silicate',
  'description': 'Groupe de silicates très fréquent dans les roches magmatiques (orthose, plagioclase).',
  'chemicalFormula': 'Variable',
  'physicalCharacteristics': 'Dureté 6, deux directions de clivage à environ 90°, faces planes brillantes.',
  'formationEnvironment': 'Roches magmatiques, métamorphiques et sédiments détritiques.',
  'commonUses': 'Céramique, verre, matériaux industriels.',
  'confirmationTests': "Deux clivages à angle droit et une dureté supérieure au couteau ; pas de réaction à l'acide.",
  'safetyWarning': "Éviter d'inhaler les poussières.",
  'luster': 'vitreous,pearly',
  'color': 'white,pink,gray,brown,green',
  'streak': 'white,none',
  'hardness': 'hard',
  'cleavage': 'two-directions',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'prismatic,massive,granular'},
 {'name': 'Galène',
  'category': 'Sulfure',
  'description': 'Sulfure de plomb gris métallique, très dense, à clivage cubique.',
  'chemicalFormula': 'PbS',
  'physicalCharacteristics': 'Dureté 2,5, très dense, éclat métallique, clivage cubique parfait, trace gris-noir.',
  'formationEnvironment': 'Veines hydrothermales et gisements polymétalliques.',
  'commonUses': 'Minerai de plomb.',
  'confirmationTests': 'Poids inhabituel pour sa taille, clivage cubique et trace noire, sans produire de poussière.',
  'safetyWarning': 'Toxique à cause du plomb : ne pas ingérer, éviter les poussières, se laver les mains.',
  'luster': 'metallic',
  'color': 'gray',
  'streak': 'black',
  'hardness': 'soft,medium',
  'cleavage': 'three-directions',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'cubic,massive'},
 {'name': 'Sphalérite',
  'category': 'Sulfure',
  'description': 'Sulfure de zinc brun à noir, à éclat résineux, principal minerai de zinc.',
  'chemicalFormula': 'ZnS',
  'physicalCharacteristics': 'Dureté 3,5 à 4, clivage parfait dans six directions, trace brun-jaune à blanche.',
  'formationEnvironment': 'Veines hydrothermales et amas sulfurés polymétalliques, souvent avec la galène.',
  'commonUses': 'Principal minerai de zinc, source de cadmium et de germanium.',
  'confirmationTests': 'Chercher les clivages multiples brillants ; trace brune claire ; elle se raye au couteau.',
  'safetyWarning': 'Peut contenir du cadmium et du plomb : éviter poussières et ingestion.',
  'luster': 'vitreous,greasy,metallic',
  'color': 'brown,black,yellow,green',
  'streak': 'brown,yellow,white',
  'hardness': 'medium',
  'cleavage': 'multiple-directions',
  'magnetic': 'no',
  'acidReaction': 'none,weak',
  'crystalHabit': 'massive,granular'},
 {'name': 'Fluorite',
  'category': 'Halogénure',
  'description': 'Fluorure de calcium très coloré (violet, vert, jaune), souvent en cubes.',
  'chemicalFormula': 'CaF₂',
  'physicalCharacteristics': 'Dureté 4, clivage octaédrique parfait dans quatre directions, souvent fluorescente sous UV.',
  'formationEnvironment': 'Veines hydrothermales, filons avec galène et barytine, pegmatites.',
  'commonUses': "Fondant en métallurgie, production d'acide fluorhydrique, optique.",
  'confirmationTests': "Elle se raye au couteau mais raye le calcaire ; pas de réaction à l'acide ; clivage en octaèdres.",
  'safetyWarning': "Éviter d'inhaler les poussières.",
  'luster': 'vitreous',
  'color': 'purple,green,transparent,yellow,blue,white,pink',
  'streak': 'white',
  'hardness': 'medium',
  'cleavage': 'multiple-directions',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'cubic,massive'},
 {'name': 'Barytine',
  'category': 'Sulfate',
  'description': 'Sulfate de baryum incolore à blanc, remarquablement dense pour un minéral clair.',
  'chemicalFormula': 'BaSO₄',
  'physicalCharacteristics': 'Dureté 3 à 3,5, densité élevée (environ 4,5), cristaux tabulaires en lames, clivages parfaits.',
  'formationEnvironment': 'Filons hydrothermaux, gisements sédimentaires et roses des sables.',
  'commonUses': 'Boues de forage pétrolier, peintures, charges, radiologie.',
  'confirmationTests': "Lourde en main pour un minéral clair ; pas de réaction à l'acide ; rayée par le couteau.",
  'safetyWarning': "Éviter d'inhaler les poussières.",
  'luster': 'vitreous,pearly',
  'color': 'white,transparent,gray,brown,yellow,blue',
  'streak': 'white',
  'hardness': 'medium',
  'cleavage': 'three-directions,two-directions',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'other,massive,prismatic'},
 {'name': 'Malachite',
  'category': 'Carbonate de cuivre',
  'description': 'Carbonate de cuivre hydraté vert vif, en croûtes mamelonnées rubanées.',
  'chemicalFormula': 'Cu₂CO₃(OH)₂',
  'physicalCharacteristics': 'Dureté 3,5 à 4, couleur verte, aspect mamelonné, trace vert pâle.',
  'formationEnvironment': "Zone d'oxydation des gisements de cuivre.",
  'commonUses': 'Minerai de cuivre secondaire, pierre ornementale, pigment.',
  'confirmationTests': "Effervescence à l'acide dilué avec une solution verte ; c'est un bon indicateur de cuivre.",
  'safetyWarning': 'Toxique si ingérée ; ne pas poncer sans protection. Acide corrosif : gants et lunettes obligatoires.',
  'luster': 'dull,vitreous',
  'color': 'green',
  'streak': 'green',
  'hardness': 'medium',
  'cleavage': 'none',
  'magnetic': 'no',
  'acidReaction': 'strong',
  'crystalHabit': 'botryoidal,massive'},
 {'name': 'Grenat',
  'category': 'Silicate',
  'description': 'Groupe de silicates en cristaux rouges à bruns, souvent en petits dodécaèdres.',
  'chemicalFormula': 'A₃B₂(SiO₄)₃',
  'physicalCharacteristics': 'Dureté 6,5 à 7,5, pas de clivage, cassure conchoïdale, cristaux arrondis à nombreuses facettes.',
  'formationEnvironment': 'Roches métamorphiques (schistes, gneiss) et certaines roches magmatiques.',
  'commonUses': "Abrasifs (jet d'eau), gemme.",
  'confirmationTests': "Il raye le verre, se présente en cristaux à 12 ou 24 faces et n'a pas de clivage.",
  'safetyWarning': "Éviter d'inhaler les poussières.",
  'luster': 'vitreous',
  'color': 'red,brown,green,pink,yellow,black',
  'streak': 'white,none',
  'hardness': 'very-hard,hard',
  'cleavage': 'none',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'granular,massive,other'},
 {'name': 'Olivine',
  'category': 'Silicate',
  'description': 'Silicate de fer et de magnésium vert olive, dominant dans le manteau supérieur.',
  'chemicalFormula': '(Mg,Fe)₂SiO₄',
  'physicalCharacteristics': 'Dureté 6,5 à 7, grains vert olive, cassure conchoïdale, pas de clivage net.',
  'formationEnvironment': 'Roches magmatiques basiques et ultrabasiques (basalte, gabbro, péridotite).',
  'commonUses': 'Réfractaires, fonderie, péridot en gemme.',
  'confirmationTests': "Grains vitreux vert olive dans une roche sombre ; elle s'altère facilement en serpentine.",
  'safetyWarning': "Éviter d'inhaler les poussières.",
  'luster': 'vitreous',
  'color': 'green,yellow,brown',
  'streak': 'white,none',
  'hardness': 'very-hard,hard',
  'cleavage': 'none',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'granular,massive'},
 {'name': 'Amphibole (hornblende)',
  'category': 'Silicate',
  'description': 'Silicate noir à vert sombre, en prismes allongés, fréquent dans les granitoïdes et les roches métamorphiques.',
  'chemicalFormula': 'Ca₂(Mg,Fe)₄Al(Si₇Al)O₂₂(OH)₂',
  'physicalCharacteristics': 'Dureté 5 à 6, deux clivages qui se coupent à 56° et 124°, cristaux allongés.',
  'formationEnvironment': 'Roches magmatiques intermédiaires (diorite, andésite) et métamorphiques (amphibolite).',
  'commonUses': 'Intérêt pétrographique.',
  'confirmationTests': 'Observer les deux clivages à 56° et 124° sur les faces ; couleur noir verdâtre.',
  'safetyWarning': 'Les variétés fibreuses (amiante) sont cancérigènes : ne pas casser ni inhaler.',
  'luster': 'vitreous',
  'color': 'black,green,brown',
  'streak': 'white',
  'hardness': 'hard',
  'cleavage': 'two-directions',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'prismatic,massive,granular'},
 {'name': 'Corindon',
  'category': 'Oxyde',
  'description': "Oxyde d'aluminium très dur, dont les variétés gemmes sont le rubis et le saphir.",
  'chemicalFormula': 'Al₂O₃',
  'physicalCharacteristics': 'Dureté 9, dense pour un minéral clair, cristaux en tonneau ou en prismes, sans vrai clivage.',
  'formationEnvironment': 'Roches métamorphiques alumineuses, syénites et pegmatites.',
  'commonUses': 'Abrasif (émeri), gemmes, céramiques techniques.',
  'confirmationTests': "Il raye facilement le quartz : la dureté suffit, aucun test destructif n'est nécessaire.",
  'safetyWarning': "Éviter d'inhaler les poussières.",
  'luster': 'vitreous',
  'color': 'gray,brown,pink,red,blue,other',
  'streak': 'none,white',
  'hardness': 'very-hard',
  'cleavage': 'none',
  'magnetic': 'no',
  'acidReaction': 'none',
  'crystalHabit': 'prismatic,massive,granular'}]

ROCKS = [{'name': 'Granite',
  'category': 'Roche magmatique',
  'description': 'Roche plutonique grenue et claire, composée surtout de quartz, de feldspath et de mica.',
  'physicalCharacteristics': 'Cristaux visibles de plusieurs millimètres, texture grenue, sans orientation.',
  'formationEnvironment': "Refroidissement lent d'un magma acide en profondeur.",
  'commonUses': 'Construction, monuments, granulats.',
  'confirmationTests': 'Repérer le quartz gris vitreux, le feldspath blanc ou rose et les paillettes de mica.',
  'safetyWarning': 'Éviter les poussières de coupe.',
  'visibleCrystals': 'yes',
  'layers': 'no',
  'foliation': 'no',
  'fossils': 'no',
  'acidReaction': 'none',
  'texture': 'coarse-grained',
  'dominantColor': 'light,intermediate',
  'visibleMinerals': 'quartz,feldspar,mica'},
 {'name': 'Diorite',
  'category': 'Roche magmatique',
  'description': "Roche plutonique grenue intermédiaire, d'aspect poivre et sel, riche en plagioclase et en amphibole.",
  'physicalCharacteristics': 'Cristaux clairs et sombres mêlés, peu ou pas de quartz.',
  'formationEnvironment': "Refroidissement lent d'un magma intermédiaire, souvent en zone de subduction.",
  'commonUses': 'Granulats, pierre ornementale.',
  'confirmationTests': "Repérer le plagioclase blanc et l'amphibole noire, avec très peu de quartz.",
  'safetyWarning': 'Éviter les poussières de coupe.',
  'visibleCrystals': 'yes',
  'layers': 'no',
  'foliation': 'no',
  'fossils': 'no',
  'acidReaction': 'none',
  'texture': 'coarse-grained',
  'dominantColor': 'intermediate,dark',
  'visibleMinerals': 'feldspar,amphibole'},
 {'name': 'Gabbro',
  'category': 'Roche magmatique',
  'description': 'Roche plutonique grenue sombre, équivalent en profondeur du basalte.',
  'physicalCharacteristics': 'Gros cristaux de pyroxène noir et de plagioclase gris, dense et sombre.',
  'formationEnvironment': "Refroidissement lent d'un magma basaltique, base de la croûte océanique.",
  'commonUses': 'Granulats, pierre ornementale (« granit noir »).',
  'confirmationTests': "Cristaux noirs de pyroxène dominants, sans quartz, aucune réaction à l'acide.",
  'safetyWarning': 'Éviter les poussières de coupe.',
  'visibleCrystals': 'yes',
  'layers': 'no',
  'foliation': 'no',
  'fossils': 'no',
  'acidReaction': 'none',
  'texture': 'coarse-grained',
  'dominantColor': 'dark',
  'visibleMinerals': 'amphibole,feldspar,olivine'},
 {'name': 'Péridotite',
  'category': 'Roche magmatique',
  'description': 'Roche ultrabasique grenue vert olive à noire, constituant principal du manteau supérieur.',
  'physicalCharacteristics': "Grains d'olivine vert olive dominants, très dense.",
  'formationEnvironment': 'Manteau supérieur, ophiolites.',
  'commonUses': 'Source de nickel et de chrome.',
  'confirmationTests': "Grains vert olive dominants, très dense, aucune réaction à l'acide ; s'altère en serpentinite.",
  'safetyWarning': "L'altération peut libérer de l'amiante (serpentinite) : prudence.",
  'visibleCrystals': 'yes',
  'layers': 'no',
  'foliation': 'no',
  'fossils': 'no',
  'acidReaction': 'none',
  'texture': 'coarse-grained',
  'dominantColor': 'dark',
  'visibleMinerals': 'olivine,amphibole'},
 {'name': 'Basalte',
  'category': 'Roche magmatique',
  'description': 'Roche volcanique sombre, à grain fin, parfois vacuolaire.',
  'physicalCharacteristics': "Texture fine, sombre, cristaux souvent invisibles, parfois des bulles ou de petits cristaux d'olivine.",
  'formationEnvironment': "Refroidissement rapide d'une lave basaltique.",
  'commonUses': 'Granulats, construction, ouvrages routiers.',
  'confirmationTests': "Observer la texture fine, les éventuelles vacuoles et l'absence de quartz.",
  'safetyWarning': 'Éviter les poussières.',
  'visibleCrystals': 'no,yes',
  'layers': 'no',
  'foliation': 'no',
  'fossils': 'no',
  'acidReaction': 'none',
  'texture': 'fine-grained,vesicular,porphyritic',
  'dominantColor': 'dark',
  'visibleMinerals': 'none,olivine,feldspar'},
 {'name': 'Andésite',
  'category': 'Roche magmatique',
  'description': 'Roche volcanique grise intermédiaire, souvent porphyrique, typique des arcs volcaniques.',
  'physicalCharacteristics': "Pâte fine grise avec des phénocristaux de feldspath ou d'amphibole.",
  'formationEnvironment': "Refroidissement rapide d'un magma intermédiaire, volcans de subduction.",
  'commonUses': 'Granulats, pierre de construction.',
  'confirmationTests': 'Chercher les phénocristaux blancs de feldspath dans une pâte grise, sans quartz visible.',
  'safetyWarning': 'Éviter les poussières.',
  'visibleCrystals': 'no,yes',
  'layers': 'no',
  'foliation': 'no',
  'fossils': 'no',
  'acidReaction': 'none',
  'texture': 'porphyritic,fine-grained',
  'dominantColor': 'intermediate,dark',
  'visibleMinerals': 'feldspar,amphibole'},
 {'name': 'Rhyolite',
  'category': 'Roche magmatique',
  'description': 'Roche volcanique claire riche en silice, équivalent effusif du granite.',
  'physicalCharacteristics': 'Pâte fine claire, parfois avec de petits cristaux de quartz ou de feldspath, aspect fluidal.',
  'formationEnvironment': "Refroidissement rapide d'une lave acide.",
  'commonUses': 'Granulats, pierre décorative.',
  'confirmationTests': "Pâte claire très fine, dure, sans réaction à l'acide ; parfois de petits quartz en phénocristaux.",
  'safetyWarning': 'Éviter les poussières de silice.',
  'visibleCrystals': 'no,yes',
  'layers': 'no',
  'foliation': 'no',
  'fossils': 'no',
  'acidReaction': 'none',
  'texture': 'fine-grained,porphyritic',
  'dominantColor': 'light,intermediate',
  'visibleMinerals': 'quartz,feldspar'},
 {'name': 'Obsidienne',
  'category': 'Roche magmatique',
  'description': 'Roche volcanique vitreuse, généralement noire.',
  'physicalCharacteristics': 'Aspect vitreux, cassure conchoïdale, aucun cristal visible.',
  'formationEnvironment': "Refroidissement très rapide d'une lave riche en silice.",
  'commonUses': 'Objets décoratifs, intérêt géologique.',
  'confirmationTests': "Observer l'aspect de verre et la cassure conchoïdale aux arêtes coupantes.",
  'safetyWarning': 'Bords cassés très coupants : manipuler avec prudence.',
  'visibleCrystals': 'no',
  'layers': 'no',
  'foliation': 'no',
  'fossils': 'no',
  'acidReaction': 'none',
  'texture': 'glassy',
  'dominantColor': 'dark',
  'visibleMinerals': 'none'},
 {'name': 'Ponce',
  'category': 'Roche magmatique',
  'description': 'Roche volcanique très poreuse formée par une lave riche en gaz.',
  'physicalCharacteristics': "Très légère, nombreuses vacuoles, elle flotte parfois sur l'eau.",
  'formationEnvironment': "Éjection et refroidissement rapide d'une lave riche en gaz.",
  'commonUses': 'Abrasifs, matériaux légers, cosmétiques.',
  'confirmationTests': "Poser sur l'eau : elle peut flotter ; observer les vacuoles.",
  'safetyWarning': 'Éviter les poussières.',
  'visibleCrystals': 'no',
  'layers': 'no',
  'foliation': 'no',
  'fossils': 'no',
  'acidReaction': 'none',
  'texture': 'vesicular',
  'dominantColor': 'light',
  'visibleMinerals': 'none'},
 {'name': 'Calcaire',
  'category': 'Roche sédimentaire',
  'description': 'Roche carbonatée souvent claire, pouvant contenir des fossiles.',
  'physicalCharacteristics': "Fine à massive, se raye au couteau, réagit à l'acide.",
  'formationEnvironment': 'Accumulation et lithification de carbonates, souvent en milieu marin.',
  'commonUses': 'Ciment, chaux, pierre de construction.',
  'confirmationTests': "Une effervescence franche lors d'un test acide réalisé en laboratoire.",
  'safetyWarning': 'Acide corrosif : gants et lunettes obligatoires.',
  'visibleCrystals': 'no,yes',
  'layers': 'yes,no',
  'foliation': 'no',
  'fossils': 'yes,no',
  'acidReaction': 'strong',
  'texture': 'fine-grained,crystalline',
  'dominantColor': 'light,intermediate',
  'visibleMinerals': 'calcite'},
 {'name': 'Dolomie',
  'category': 'Roche sédimentaire',
  'description': 'Roche carbonatée composée surtout de dolomite, souvent plus grenue et plus dure que le calcaire.',
  'physicalCharacteristics': 'Grain plus sucré que le calcaire, souvent gris jaunâtre, altération en surface sableuse.',
  'formationEnvironment': "Transformation d'un calcaire par des fluides magnésiens, ou précipitation en milieu évaporitique.",
  'commonUses': 'Pierre de construction, granulats, fondant.',
  'confirmationTests': "Réaction faible ou absente sur un échantillon massif lors d'un test acide encadré.",
  'safetyWarning': 'Acide corrosif : gants et lunettes obligatoires.',
  'visibleCrystals': 'no,yes',
  'layers': 'yes,no',
  'foliation': 'no',
  'fossils': 'no,yes',
  'acidReaction': 'weak',
  'texture': 'crystalline,fine-grained',
  'dominantColor': 'light,intermediate',
  'visibleMinerals': 'calcite,none'},
 {'name': 'Grès',
  'category': 'Roche sédimentaire',
  'description': 'Roche détritique constituée principalement de grains de sable cimentés.',
  'physicalCharacteristics': 'Texture clastique, grains de sable visibles et rugueux au toucher.',
  'formationEnvironment': 'Dépôt de sable puis lithification.',
  'commonUses': "Construction, pierre décorative, réservoirs d'eau et d'hydrocarbures.",
  'confirmationTests': "Les grains de quartz se voient à la loupe ; la roche est rugueuse ; pas de réaction à l'acide (sauf ciment "
                       'calcaire).',
  'safetyWarning': 'Éviter les poussières de silice.',
  'visibleCrystals': 'no',
  'layers': 'yes,no',
  'foliation': 'no',
  'fossils': 'no',
  'acidReaction': 'none,weak',
  'texture': 'clastic',
  'dominantColor': 'light,intermediate',
  'visibleMinerals': 'quartz'},
 {'name': 'Conglomérat',
  'category': 'Roche sédimentaire',
  'description': 'Roche détritique formée de galets arrondis cimentés dans une matrice sableuse.',
  'physicalCharacteristics': 'Galets arrondis de plusieurs millimètres à centimètres dans un ciment.',
  'formationEnvironment': "Dépôt de graviers par des cours d'eau ou des plages, puis lithification.",
  'commonUses': 'Construction, pierre décorative.',
  'confirmationTests': 'Repérer les galets arrondis empâtés dans une matrice ; les fragments anguleux forment une brèche.',
  'safetyWarning': 'Éviter les poussières.',
  'visibleCrystals': 'no',
  'layers': 'yes,no',
  'foliation': 'no',
  'fossils': 'no',
  'acidReaction': 'none,weak',
  'texture': 'clastic-coarse',
  'dominantColor': 'intermediate,light,dark',
  'visibleMinerals': 'quartz,none'},
 {'name': 'Argilite (shale)',
  'category': 'Roche sédimentaire',
  'description': 'Roche sédimentaire très fine, terreuse, se délitant en plaquettes.',
  'physicalCharacteristics': "Grain invisible, fissile, souvent grise à noire, se raye à l'ongle ou au couteau.",
  'formationEnvironment': 'Dépôt de boues argileuses en milieu calme, puis compaction.',
  'commonUses': 'Briques, tuiles, roche mère de pétrole.',
  'confirmationTests': "Se délite en plaquettes, odeur d'argile mouillée, aucune réaction à l'acide.",
  'safetyWarning': 'Éviter les poussières.',
  'visibleCrystals': 'no',
  'layers': 'yes',
  'foliation': 'no',
  'fossils': 'no,yes',
  'acidReaction': 'none',
  'texture': 'clastic-fine',
  'dominantColor': 'dark,intermediate',
  'visibleMinerals': 'none'},
 {'name': 'Silex (chert)',
  'category': 'Roche sédimentaire',
  'description': 'Roche siliceuse très dure, à cassure conchoïdale, en rognons ou en bancs.',
  'physicalCharacteristics': 'Grain très fin, cassure conchoïdale à arêtes vives, aspect cireux ou vitreux.',
  'formationEnvironment': 'Précipitation de silice en milieu marin, souvent au sein de calcaires.',
  'commonUses': 'Outils préhistoriques, granulats, pierre à feu.',
  'confirmationTests': "Il raye l'acier et le verre, casse en éclats tranchants, aucune réaction à l'acide.",
  'safetyWarning': 'Éclats tranchants : porter des gants et des lunettes.',
  'visibleCrystals': 'no',
  'layers': 'no,yes',
  'foliation': 'no',
  'fossils': 'no,yes',
  'acidReaction': 'none',
  'texture': 'fine-grained,glassy',
  'dominantColor': 'dark,intermediate,light',
  'visibleMinerals': 'quartz,none'},
 {'name': 'Marbre',
  'category': 'Roche métamorphique',
  'description': "Roche carbonatée recristallisée, souvent issue d'un calcaire.",
  'physicalCharacteristics': 'Mosaïque de cristaux de calcite, aspect sucré, parfois veiné.',
  'formationEnvironment': 'Métamorphisme de roches carbonatées.',
  'commonUses': 'Sculpture, décoration, construction.',
  'confirmationTests': 'Réaction franche à un test acide encadré et texture cristalline sucrée.',
  'safetyWarning': 'Acide corrosif : gants et lunettes obligatoires.',
  'visibleCrystals': 'yes',
  'layers': 'no',
  'foliation': 'no',
  'fossils': 'no',
  'acidReaction': 'strong',
  'texture': 'crystalline',
  'dominantColor': 'light',
  'visibleMinerals': 'calcite'},
 {'name': 'Quartzite',
  'category': 'Roche métamorphique',
  'description': 'Roche métamorphique très dure, composée presque uniquement de quartz.',
  'physicalCharacteristics': 'Texture cristalline sucrée, cassure à travers les grains, très résistante.',
  'formationEnvironment': 'Métamorphisme de grès riches en quartz.',
  'commonUses': 'Construction, pierre décorative, ballast.',
  'confirmationTests': "Elle raye le verre et l'acier, ne réagit pas à l'acide et casse à travers les grains.",
  'safetyWarning': 'Éviter les poussières de silice.',
  'visibleCrystals': 'yes',
  'layers': 'no',
  'foliation': 'no',
  'fossils': 'no',
  'acidReaction': 'none',
  'texture': 'crystalline',
  'dominantColor': 'light,intermediate',
  'visibleMinerals': 'quartz'},
 {'name': 'Gneiss',
  'category': 'Roche métamorphique',
  'description': 'Roche métamorphique à alternance de bandes claires et foncées.',
  'physicalCharacteristics': 'Foliation en bandes marquées, gros cristaux visibles de quartz et de feldspath.',
  'formationEnvironment': 'Métamorphisme régional de haute température et haute pression.',
  'commonUses': 'Construction, pierre décorative.',
  'confirmationTests': 'Observer les bandes claires (quartz, feldspath) et sombres (mica, amphibole).',
  'safetyWarning': 'Éviter les poussières.',
  'visibleCrystals': 'yes',
  'layers': 'no',
  'foliation': 'yes',
  'fossils': 'no',
  'acidReaction': 'none',
  'texture': 'foliated',
  'dominantColor': 'intermediate,light',
  'visibleMinerals': 'feldspar,quartz,mica'},
 {'name': 'Schiste (micaschiste)',
  'category': 'Roche métamorphique',
  'description': 'Roche métamorphique feuilletée, riche en paillettes de mica, qui brillent sur les plans de rupture.',
  'physicalCharacteristics': 'Foliation nette, surfaces brillantes de mica, se débite en plaques irrégulières.',
  'formationEnvironment': 'Métamorphisme régional de roches argileuses, à intensité moyenne.',
  'commonUses': 'Dallage, pierre de construction.',
  'confirmationTests': 'Les plans de foliation brillent de paillettes de mica ; parfois des grenats rouges.',
  'safetyWarning': 'Éviter les poussières.',
  'visibleCrystals': 'yes',
  'layers': 'no',
  'foliation': 'yes',
  'fossils': 'no',
  'acidReaction': 'none',
  'texture': 'foliated',
  'dominantColor': 'intermediate,dark',
  'visibleMinerals': 'mica,quartz,garnet'},
 {'name': 'Ardoise',
  'category': 'Roche métamorphique',
  'description': 'Roche métamorphique très fine, à débit régulier en feuillets minces.',
  'physicalCharacteristics': 'Grain invisible, surfaces planes et mates, débit en dalles minces.',
  'formationEnvironment': 'Métamorphisme faible de roches argileuses.',
  'commonUses': 'Toitures, dallage, décoration.',
  'confirmationTests': 'Elle se débite en feuillets minces et réguliers ; sonne clair quand on la frappe.',
  'safetyWarning': 'Éviter les poussières lors de la découpe.',
  'visibleCrystals': 'no',
  'layers': 'no',
  'foliation': 'yes',
  'fossils': 'no',
  'acidReaction': 'none',
  'texture': 'foliated',
  'dominantColor': 'dark',
  'visibleMinerals': 'none'}]

QUESTION_CATALOG = {'minerals': [('color',
               'Quelle est la couleur dominante ?',
               'Regardez une cassure fraîche si possible : une surface altérée peut tromper.',
               [('white', 'Blanc', None, '#f4f5f2'),
                ('transparent', 'Transparent', 'Incolore, on voit à travers', 'checker'),
                ('gray', 'Gris', None, '#8b9298'),
                ('black', 'Noir', None, '#1d1f22'),
                ('yellow', 'Jaune', 'Jaune laiton ou jaune vif', '#dcb52a'),
                ('brown', 'Brun', None, '#7a5230'),
                ('green', 'Vert', None, '#2e8b57'),
                ('red', 'Rouge', None, '#b3382c'),
                ('pink', 'Rose', None, '#e5a3b4'),
                ('purple', 'Violet', None, '#7b4fa1'),
                ('blue', 'Bleu', None, '#2f6db5'),
                ('other', 'Autre / multicolore', None, 'rainbow')]),
              ('luster',
               'Comment brille la surface ?',
               "Tournez l'échantillon vers la lumière. Un éclat métallique ressemble à un métal poli, même si le minéral est sombre.",
               [('metallic', 'Métallique', 'Comme un métal poli', None),
                ('vitreous', 'Vitreux', 'Comme du verre', None),
                ('pearly', 'Nacré ou soyeux', 'Reflets de nacre', None),
                ('greasy', 'Gras', "Comme s'il était huilé", None),
                ('dull', 'Mat ou terreux', 'Sans brillance', None),
                ('non-metallic', 'Non métallique', 'Pas un métal, sans plus de précision', None)]),
              ('crystalHabit',
               'Quelle forme prend le minéral ?',
               "Observez la forme des cristaux, ou de l'ensemble s'ils ne sont pas visibles.",
               [('cubic', 'Cubique', 'Cubes ou dés', None),
                ('prismatic', 'Prismatique', 'Colonnes ou aiguilles allongées', None),
                ('flaky', 'Feuilleté', 'Lamelles qui se détachent', None),
                ('granular', 'Grenu', 'Petits grains agglomérés', None),
                ('massive', 'Massif', 'Pas de forme régulière visible', None),
                ('botryoidal', 'Mamelonné', 'Boules ou grappes arrondies', None),
                ('other', 'Autre', None, None)]),
              ('hardness',
               'Quelle est sa dureté ?',
               "Essayez dans l'ordre : ongle, pièce de cuivre ou couteau, puis verre. Choisissez le meilleur résultat.",
               [('soft', 'Tendre', "Rayé par l'ongle · Mohs 1 à 2,5", None),
                ('medium', 'Moyenne', "Résiste à l'ongle, rayé par un couteau · Mohs 3 à 5", None),
                ('hard', 'Dure', 'Résiste au couteau, raye à peine le verre · Mohs 5,5 à 6,5', None),
                ('very-hard', 'Très dure', 'Raye nettement le verre · Mohs 7 et plus', None)]),
              ('streak',
               'Quelle est la couleur de la trace ?',
               "Frottez l'échantillon sur une plaque de porcelaine non émaillée (le dos d'un carreau) : la poudre laissée révèle la vraie "
               'couleur.',
               [('white', 'Blanche', None, '#f4f5f2'),
                ('black', 'Noire ou gris foncé', None, '#26282b'),
                ('red-brown', 'Rouge-brun', None, '#8e3b26'),
                ('brown', 'Brune ou jaune-brun', None, '#a8783c'),
                ('yellow', 'Jaune', None, '#e2c04a'),
                ('green', 'Verte', None, '#5f9a6e'),
                ('none', 'Aucune trace', 'Minéral plus dur que la plaque', None)]),
              ('cleavage',
               'Comment se casse-t-il ?',
               "Cherchez des surfaces planes et brillantes qui se répètent quand on tourne l'échantillon.",
               [('none', 'Aucun clivage', 'Cassure irrégulière ou en coquille', None),
                ('one-direction', 'Une direction', 'Se débite en feuillets', None),
                ('two-directions', 'Deux directions', 'Éclats en prismes, souvent à angle droit', None),
                ('three-directions', 'Trois directions', 'Blocs en cubes ou en rhomboèdres', None),
                ('multiple-directions', 'Plus de trois directions', 'Octaèdres ou dodécaèdres', None)]),
              ('magnetic',
               "Un aimant l'attire-t-il ?",
               "Approchez un petit aimant, ou une boussole de l'échantillon.",
               [('yes', 'Oui', 'Attiré nettement', None), ('no', 'Non', 'Aucune attraction', None)]),
              ('acidReaction',
               "Réagit-il à l'acide dilué ?",
               "Ne réalisez pas un test à l'acide vous-même. Pour une identification réelle, faites effectuer ce test par un enseignant ou "
               'un laboratoire équipé.',
               [('strong', 'Forte', 'Effervescence franche', None),
                ('weak', 'Faible', 'Réaction légère ou localisée', None),
                ('none', 'Aucune', 'Aucune réaction observée', None)])],
 'rocks': [('texture',
            'Quelle est la texture de la roche ?',
            'Observez la taille et la disposition des grains, si possible avec une loupe.',
            [('coarse-grained', 'Grenue', 'Gros cristaux imbriqués', None),
             ('porphyritic', 'Porphyrique', 'Gros cristaux dans une pâte fine', None),
             ('fine-grained', 'Fine', "Grains invisibles à l'œil nu", None),
             ('glassy', 'Vitreuse', 'Aspect de verre', None),
             ('vesicular', 'Vacuolaire', 'Trous laissés par des bulles de gaz', None),
             ('clastic', 'Sableuse', 'Grains de sable cimentés', None),
             ('clastic-coarse', 'À galets', 'Galets ou graviers cimentés', None),
             ('clastic-fine', 'Argileuse', 'Très fine, terreuse, se délite', None),
             ('foliated', 'Feuilletée', 'Minéraux alignés en feuillets ou en bandes', None),
             ('crystalline', 'Cristalline', 'Mosaïque de cristaux, aspect sucré', None)]),
           ('dominantColor',
            'Quelle est la teinte générale ?',
            'Regardez la roche dans son ensemble, pas un seul cristal.',
            [('light', 'Claire', 'Blanc, beige, rose, gris clair', '#e4e1d8'),
             ('intermediate', 'Intermédiaire', 'Gris moyen, mélange de clair et de foncé', '#9a9b96'),
             ('dark', 'Foncée', 'Noir, gris foncé, vert sombre', '#30343a')]),
           ('visibleMinerals',
            'Quel minéral voyez-vous surtout ?',
            'Choisissez celui qui domine parmi les cristaux ou les grains identifiables.',
            [('quartz', 'Quartz', 'Gris vitreux, sans clivage', None),
             ('feldspar', 'Feldspath', 'Blanc ou rose, faces planes brillantes', None),
             ('mica', 'Mica', 'Paillettes brillantes', None),
             ('calcite', 'Calcite', "Blanche, réagit à l'acide", None),
             ('olivine', 'Olivine', 'Grains vert olive', None),
             ('amphibole', 'Amphibole ou pyroxène', 'Cristaux noirs ou vert sombre', None),
             ('garnet', 'Grenat', 'Petits cristaux rouges', None),
             ('none', 'Aucun', "Rien d'identifiable", None)]),
           ('visibleCrystals',
            "Voit-on des cristaux à l'œil nu ?",
            'Des cristaux, pas seulement des grains de sable arrondis.',
            [('yes', 'Oui', 'Cristaux bien visibles', None), ('no', 'Non', 'Grains trop fins ou absents', None)]),
           ('layers',
            'Voit-on des couches ?',
            'Des lits successifs, comme des strates empilées.',
            [('yes', 'Oui', 'Lits ou strates visibles', None), ('no', 'Non', 'Aspect massif ou homogène', None)]),
           ('foliation',
            'Y a-t-il des bandes ou des feuillets ?',
            'Des minéraux alignés, une roche qui se débite en plaques.',
            [('yes', 'Oui', 'Rubans ou feuillets alignés', None), ('no', 'Non', "Pas d'alignement", None)]),
           ('fossils',
            'Voit-on des fossiles ?',
            "Coquilles, empreintes, fragments d'organismes.",
            [('yes', 'Oui', 'Fossiles reconnaissables', None), ('no', 'Non', 'Aucun fossile', None)]),
           ('acidReaction',
            "Réagit-elle à l'acide dilué ?",
            "Ne réalisez pas un test à l'acide vous-même. Pour une identification réelle, faites effectuer ce test par un enseignant ou un "
            'laboratoire équipé.',
            [('strong', 'Forte', 'Effervescence franche', None),
             ('weak', 'Faible', 'Réaction légère ou localisée', None),
             ('none', 'Aucune', 'Aucune réaction observée', None)])]}

# ---------------------------------------------------------------------------
# GeoIdentify expanded local reference catalog
# ---------------------------------------------------------------------------
# The original 43 records are retained. These additional records make the
# classifier useful across a much wider range of common minerals and rocks.
# "All minerals/rocks" is not a finite practical target: mineralogy contains
# thousands of species and rocks have many varieties. This catalog is therefore
# intentionally broad and can be extended without changing the engine.


def _mineral(name, category, formula, color, luster, streak, hardness, cleavage,
             magnetic, acid, habit, transparency="opaque", density="medium",
             fracture="uneven", magnetic_strength="none"):
    return {
        "name": name, "category": category, "description": f"Référence de terrain pour {name}.",
        "chemicalFormula": formula, "physicalCharacteristics": f"Dureté {hardness}; éclat {luster}; trace {streak}.",
        "formationEnvironment": "Présent dans différents contextes géologiques; consulter une référence pétrographique pour le contexte précis.",
        "commonUses": "Usage variable selon la qualité et le contexte.",
        "confirmationTests": "Comparer plusieurs propriétés diagnostiques et, si nécessaire, confirmer en laboratoire.",
        "safetyWarning": "Éviter l'inhalation de poussières et les tests chimiques non supervisés.",
        "luster": luster, "color": color, "streak": streak, "hardness": hardness,
        "cleavage": cleavage, "magnetic": magnetic, "acidReaction": acid,
        "crystalHabit": habit, "transparency": transparency, "density": density,
        "fracture": fracture, "magneticStrength": magnetic_strength,
    }


def _rock(name, category, texture, color, visible_minerals, crystals, layers,
          foliation, fossils, acid, rock_type, grain_size, vesicles="no",
          sorting="mixed", rounding="angular"):
    return {
        "name": name, "category": category,
        "description": f"Référence de terrain pour {name}.",
        "physicalCharacteristics": f"Texture {texture}; teinte {color}; minéraux visibles: {visible_minerals}.",
        "formationEnvironment": "Contexte de formation variable; utiliser les caractères pétrographiques pour confirmer.",
        "commonUses": "Usage variable selon le matériau et le contexte.",
        "confirmationTests": "Comparer texture, minéraux, structure et contexte géologique; confirmer en laboratoire si nécessaire.",
        "safetyWarning": "Éviter l'inhalation de poussières lors de la coupe ou du broyage.",
        "visibleCrystals": crystals, "layers": layers, "foliation": foliation,
        "fossils": fossils, "acidReaction": acid, "texture": texture,
        "dominantColor": color, "visibleMinerals": visible_minerals,
        "rockType": rock_type, "grainSize": grain_size, "vesicles": vesicles,
        "sorting": sorting, "rounding": rounding,
    }


_EXTRA_MINERALS = [
    _mineral("Orthoclase", "Silicate", "KAlSi₃O₈", "white,pink", "vitreous", "white", "hard", "two-directions", "no", "none", "prismatic,massive", "translucent", "medium"),
    _mineral("Microcline", "Silicate", "KAlSi₃O₈", "white,pink,green", "vitreous", "white", "hard", "two-directions", "no", "none", "prismatic,massive", "translucent", "medium"),
    _mineral("Albite", "Silicate", "NaAlSi₃O₈", "white,gray", "vitreous", "white", "hard", "two-directions", "no", "none", "prismatic", "translucent", "medium"),
    _mineral("Anorthite", "Silicate", "CaAl₂Si₂O₈", "white,gray", "vitreous", "white", "hard", "two-directions", "no", "none", "prismatic", "translucent", "medium"),
    _mineral("Biotite", "Silicate", "K(Mg,Fe)₃AlSi₃O₁₀(F,OH)₂", "black,brown", "pearly", "white,gray", "medium", "one-direction", "no", "none", "flaky", "opaque", "medium"),
    _mineral("Muscovite", "Silicate", "KAl₂(AlSi₃O₁₀)(F,OH)₂", "transparent,white", "pearly", "white", "medium", "one-direction", "no", "none", "flaky", "transparent", "medium"),
    _mineral("Kaolinite", "Clay", "Al₂Si₂O₅(OH)₄", "white", "dull", "white", "soft", "one-direction", "no", "none", "massive,flaky", "translucent", "light"),
    _mineral("Illite", "Clay", "KAl₂(AlSi₃O₁₀)(OH)₂", "white,gray", "pearly,dull", "white", "soft", "one-direction", "no", "none", "flaky", "translucent", "light"),
    _mineral("Montmorillonite", "Clay", "(Na,Ca)₀.₃(Al,Mg)₂Si₄O₁₀(OH)₂·nH₂O", "white,gray", "dull", "white", "soft", "one-direction", "no", "none", "massive", "translucent", "light"),
    _mineral("Serpentine", "Silicate", "Mg₃Si₂O₅(OH)₄", "green,yellow", "greasy,pearly", "white", "soft", "one-direction", "no", "none", "massive,flaky", "translucent", "medium"),
    _mineral("Chlorite", "Silicate", "(Mg,Fe,Al)₆(Si,Al)₄O₁₀(OH)₈", "green,gray", "pearly", "white,gray", "soft", "one-direction", "no", "none", "flaky", "translucent", "medium"),
    _mineral("Epidote", "Silicate", "Ca₂(Al,Fe)₃Si₃O₁₂(OH)", "green,yellow", "vitreous", "white", "hard", "one-direction", "no", "none", "prismatic", "translucent", "heavy"),
    _mineral("Actinolite", "Silicate", "Ca₂(Mg,Fe)₅Si₈O₂₂(OH)₂", "green", "vitreous", "white", "hard", "two-directions", "no", "none", "prismatic", "translucent", "heavy"),
    _mineral("Tremolite", "Silicate", "Ca₂Mg₅Si₈O₂₂(OH)₂", "white,gray,green", "vitreous,pearly", "white", "hard", "two-directions", "no", "none", "prismatic", "translucent", "heavy"),
    _mineral("Augite", "Silicate", "(Ca,Na)(Mg,Fe,Al)(Si,Al)₂O₆", "black,green", "vitreous", "gray", "hard", "two-directions", "no", "none", "prismatic", "translucent", "heavy"),
    _mineral("Diopside", "Silicate", "CaMgSi₂O₆", "green,white", "vitreous", "white", "hard", "two-directions", "no", "none", "prismatic", "translucent", "heavy"),
    _mineral("Enstatite", "Silicate", "MgSiO₃", "brown,green,gray", "vitreous", "white,gray", "hard", "two-directions", "no", "none", "prismatic", "translucent", "medium"),
    _mineral("Spodumene", "Silicate", "LiAlSi₂O₆", "white,green,pink", "vitreous", "white", "hard", "two-directions", "no", "none", "prismatic", "translucent", "medium"),
    _mineral("Beryl", "Silicate", "Be₃Al₂Si₆O₁₈", "green,blue,yellow", "vitreous", "white", "very-hard", "none", "no", "none", "prismatic", "transparent", "medium"),
    _mineral("Tourmaline", "Silicate", "complex borosilicate", "black,green,pink", "vitreous", "white", "very-hard", "none", "no", "none", "prismatic", "transparent", "medium"),
    _mineral("Zircon", "Silicate", "ZrSiO₄", "brown,red,transparent", "adamantine", "white", "very-hard", "no", "none", "prismatic", "transparent", "heavy"),
    _mineral("Titanite", "Silicate", "CaTiSiO₅", "brown,green,yellow", "resinous", "white", "hard", "one-direction", "no", "none", "wedge", "transparent", "heavy"),
    _mineral("Topaz", "Silicate", "Al₂SiO₄(F,OH)₂", "transparent,white,yellow,blue", "vitreous", "white", "very-hard", "two-directions", "no", "none", "prismatic", "transparent", "heavy"),
    _mineral("Beryl (var. émeraude)", "Silicate", "Be₃Al₂Si₆O₁₈", "green", "vitreous", "white", "very-hard", "none", "no", "none", "prismatic", "transparent", "medium"),
    _mineral("Kyanite", "Silicate", "Al₂SiO₅", "blue,gray,white", "vitreous", "white", "hard", "one-direction", "no", "none", "bladed", "translucent", "medium"),
    _mineral("Andalousite", "Silicate", "Al₂SiO₅", "brown,green,pink", "vitreous", "white", "hard", "two-directions", "no", "none", "prismatic", "transparent", "medium"),
    _mineral("Sillimanite", "Silicate", "Al₂SiO₅", "white,gray,brown", "vitreous", "white", "hard", "one-direction", "no", "none", "fibrous,prismatic", "translucent", "medium"),
    _mineral("Staurolite", "Silicate", "(Fe,Mg)₂Al₉Si₄O₂₂(OH)₂", "brown,black", "resinous", "white", "hard", "two-directions", "no", "none", "prismatic", "opaque", "heavy"),
    _mineral("Cordierite", "Silicate", "(Mg,Fe)₂Al₄Si₅O₁₈", "blue,gray,brown", "vitreous", "white", "hard", "none", "no", "none", "prismatic", "transparent", "medium"),
    _mineral("Prehnite", "Silicate", "Ca₂Al₂Si₃O₁₀(OH)₂", "green,white", "pearly", "white", "medium", "one-direction", "no", "none", "botryoidal,massive", "translucent", "medium"),
    _mineral("Zeolite", "Silicate", "hydrated aluminosilicate", "white,green,pink", "pearly", "white", "soft", "one-direction", "no", "none", "prismatic,botryoidal", "translucent", "light"),
    _mineral("Apatite", "Phosphate", "Ca₅(PO₄)₃(F,Cl,OH)", "green,blue,brown", "vitreous", "white", "medium", "one-direction", "no", "none", "prismatic", "transparent", "medium"),
    _mineral("Monazite", "Phosphate", "(Ce,La,Nd,Th)PO₄", "yellow,brown", "resinous", "white", "hard", "one-direction", "no", "none", "prismatic", "translucent", "heavy"),
    _mineral("Barite", "Sulfate", "BaSO₄", "white,blue,brown", "vitreous,pearly", "white", "soft", "three-directions", "no", "none", "tabular", "translucent", "heavy"),
    _mineral("Celestine", "Sulfate", "SrSO₄", "blue,white", "vitreous", "white", "soft", "three-directions", "no", "none", "tabular", "transparent", "heavy"),
    _mineral("Fluorapatite", "Phosphate", "Ca₅(PO₄)₃F", "green,blue", "vitreous", "white", "medium", "one-direction", "no", "none", "prismatic", "transparent", "medium"),
    _mineral("Aragonite", "Carbonate", "CaCO₃", "white,transparent,brown", "vitreous", "white", "medium", "three-directions", "no", "strong", "prismatic,acicular", "transparent", "medium"),
    _mineral("Siderite", "Carbonate", "FeCO₃", "brown,gray,yellow", "vitreous,pearly", "white", "medium", "three-directions", "weak", "weak", "rhombohedral,massive", "translucent", "heavy"),
    _mineral("Rhodochrosite", "Carbonate", "MnCO₃", "pink,red,white", "vitreous,pearly", "white", "medium", "three-directions", "no", "strong", "rhombohedral,banded", "translucent", "medium"),
    _mineral("Smithsonite", "Carbonate", "ZnCO₃", "white,green,blue", "vitreous,pearly", "white", "soft", "three-directions", "no", "strong", "botryoidal,massive", "translucent", "heavy"),
    _mineral("Cerussite", "Carbonate", "PbCO₃", "white,gray", "adamantine", "white", "soft", "two-directions", "no", "strong", "prismatic", "transparent", "heavy"),
    _mineral("Anglesite", "Sulfate", "PbSO₄", "white,gray,yellow", "adamantine", "white", "soft", "three-directions", "no", "none", "prismatic", "transparent", "heavy"),
    _mineral("Cinnabar", "Sulfure", "HgS", "red,brown", "adamantine", "red", "soft", "none", "no", "none", "massive,granular", "opaque", "heavy"),
    _mineral("Realgar", "Sulfure", "As₄S₄", "red,orange", "resinous", "orange", "soft", "none", "no", "none", "prismatic,massive", "translucent", "heavy"),
    _mineral("Orpiment", "Sulfure", "As₂S₃", "yellow", "resinous", "yellow", "soft", "one-direction", "no", "none", "foliated,massive", "translucent", "heavy"),
    _mineral("Molybdénite", "Sulfure", "MoS₂", "gray,black", "metallic", "gray", "soft", "one-direction", "no", "none", "flaky", "opaque", "heavy"),
    _mineral("Bornite", "Sulfure", "Cu₅FeS₄", "purple,blue,brown", "metallic", "gray,black", "medium", "none", "no", "none", "massive,granular", "opaque", "heavy"),
    _mineral("Covellite", "Sulfure", "CuS", "blue,black", "metallic", "gray,black", "soft", "one-direction", "no", "none", "platy,massive", "opaque", "heavy"),
    _mineral("Tétraédrite", "Sulfure", "Cu₁₂Sb₄S₁₃", "gray,black", "metallic", "black", "medium", "none", "no", "none", "tetrahedral,massive", "opaque", "heavy"),
    _mineral("Cassitérite", "Oxyde", "SnO₂", "black,brown,red", "adamantine", "white,brown", "hard", "none", "no", "none", "prismatic,granular", "translucent", "heavy"),
    _mineral("Chromite", "Oxyde", "FeCr₂O₄", "black,brown", "metallic", "brown", "hard", "none", "weak", "none", "octahedral,massive", "opaque", "heavy", "weak"),
    _mineral("Ilménite", "Oxyde", "FeTiO₃", "black,gray", "metallic", "black,brown", "hard", "none", "weak", "none", "tabular,massive", "opaque", "heavy", "weak"),
    _mineral("Rutile", "Oxyde", "TiO₂", "red,brown,black", "adamantine", "brown", "hard", "none", "no", "none", "prismatic,acicular", "transparent", "heavy"),
    _mineral("Goethite", "Oxyde", "FeO(OH)", "brown,yellow,black", "dull,metallic", "yellow,brown", "medium", "none", "weak", "none", "botryoidal,earthy", "opaque", "heavy", "weak"),
    _mineral("Cuprite", "Oxyde", "Cu₂O", "red,brown", "adamantine", "red-brown", "medium", "none", "no", "none", "cubic,granular", "translucent", "heavy"),
    _mineral("Spinelle", "Oxyde", "MgAl₂O₄", "red,black,blue", "vitreous", "white", "very-hard", "none", "no", "none", "octahedral", "transparent", "medium"),
    _mineral("Periclase", "Oxyde", "MgO", "white,gray,green", "vitreous", "white", "hard", "three-directions", "no", "none", "cubic,massive", "translucent", "medium"),
    _mineral("Native copper", "Élément natif", "Cu", "red,brown", "metallic", "red", "medium", "none", "no", "none", "massive,wire", "opaque", "heavy"),
    _mineral("Native silver", "Élément natif", "Ag", "gray,white", "metallic", "gray", "soft", "none", "no", "none", "wire,massive", "opaque", "heavy"),
    _mineral("Soufre natif", "Élément natif", "S", "yellow", "resinous", "yellow", "soft", "none", "no", "none", "massive,crystalline", "translucent", "medium"),
    _mineral("Graphite", "Élément natif", "C", "gray,black", "metallic", "black", "soft", "one-direction", "no", "none", "flaky,massive", "opaque", "light"),
]

_EXTRA_ROCKS = [
    _rock("Syénite", "Roche magmatique", "coarse-grained", "light", "feldspar", "yes", "no", "no", "no", "none", "igneous", "coarse"),
    _rock("Monzonite", "Roche magmatique", "coarse-grained", "intermediate", "feldspar,biotite", "yes", "no", "no", "no", "none", "igneous", "coarse"),
    _rock("Granodiorite", "Roche magmatique", "coarse-grained", "light", "quartz,feldspar", "yes", "no", "no", "no", "none", "igneous", "coarse"),
    _rock("Tonalite", "Roche magmatique", "coarse-grained", "light", "quartz,feldspar", "yes", "no", "no", "no", "none", "igneous", "coarse"),
    _rock("Pegmatite", "Roche magmatique", "coarse-grained", "light", "feldspar,quartz,mica", "yes", "no", "no", "no", "none", "igneous", "very-coarse"),
    _rock("Aplite", "Roche magmatique", "fine-grained", "light", "quartz,feldspar", "no", "no", "no", "no", "none", "igneous", "fine"),
    _rock("Dacite", "Roche magmatique", "porphyritic", "light", "quartz,feldspar", "yes", "no", "no", "no", "none", "igneous", "fine"),
    _rock("Trachyte", "Roche magmatique", "porphyritic", "light", "feldspar", "yes", "no", "no", "no", "none", "igneous", "fine"),
    _rock("Komatiite", "Roche magmatique", "fine-grained", "dark", "olivine", "no", "no", "no", "no", "none", "igneous", "fine"),
    _rock("Tuf volcanique", "Roche volcanoclastique", "clastic-fine", "intermediate", "feldspar", "no", "no", "no", "no", "none", "volcanic", "fine"),
    _rock("Ignimbrite", "Roche volcanoclastique", "clastic-fine", "light", "quartz,feldspar", "no", "no", "no", "no", "none", "volcanic", "fine"),
    _rock("Scorie", "Roche volcanique", "vesicular", "dark", "none", "no", "no", "no", "no", "none", "igneous", "fine", "yes"),
    _rock("Agglomérat volcanique", "Roche volcanoclastique", "clastic-coarse", "dark", "feldspar,amphibole", "yes", "no", "no", "no", "none", "volcanic", "coarse", "poorly-sorted", "rounded"),
    _rock("Tuffite", "Roche volcanoclastique", "clastic-fine", "intermediate", "feldspar", "no", "no", "no", "no", "none", "volcanic", "fine"),
    _rock("Calcarenite", "Roche sédimentaire", "clastic", "light", "calcite", "no", "yes", "no", "sometimes", "strong", "sedimentary", "fine", "no", "well-sorted", "rounded"),
    _rock("Marne", "Roche sédimentaire", "clastic-fine", "intermediate", "calcite", "no", "yes", "no", "sometimes", "strong", "sedimentary", "fine"),
    _rock("Siltite", "Roche sédimentaire", "clastic-fine", "intermediate", "quartz", "no", "yes", "no", "rare", "none", "sedimentary", "very-fine", "no", "well-sorted", "rounded"),
    _rock("Arkose", "Roche sédimentaire", "clastic", "light", "feldspar,quartz", "no", "yes", "no", "no", "none", "sedimentary", "medium", "no", "poorly-sorted", "angular"),
    _rock("Grauwacke", "Roche sédimentaire", "clastic", "dark", "quartz,feldspar,mica", "no", "no", "no", "no", "none", "sedimentary", "medium", "no", "poorly-sorted", "angular"),
    _rock("Brèche", "Roche sédimentaire", "clastic-coarse", "intermediate", "quartz,feldspar", "yes", "no", "no", "no", "none", "sedimentary", "coarse", "no", "poorly-sorted", "angular"),
    _rock("Travertin", "Roche sédimentaire", "crystalline", "light", "calcite", "yes", "yes", "no", "sometimes", "strong", "sedimentary", "fine"),
    _rock("Diatomite", "Roche sédimentaire", "clastic-fine", "light", "none", "no", "yes", "no", "yes", "none", "sedimentary", "very-fine"),
    _rock("Evaporite", "Roche sédimentaire", "crystalline", "light", "halite,gypse", "yes", "yes", "no", "no", "none", "sedimentary", "fine"),
    _rock("Charbon", "Roche sédimentaire", "clastic-fine", "dark", "none", "no", "yes", "no", "no", "none", "sedimentary", "fine"),
    _rock("Phosphorite", "Roche sédimentaire", "clastic", "intermediate", "apatite,calcite", "no", "yes", "no", "sometimes", "weak", "sedimentary", "fine"),
    _rock("Pélite", "Roche sédimentaire", "clastic-fine", "dark", "clay", "no", "yes", "no", "rare", "none", "sedimentary", "very-fine"),
    _rock("Filon de quartz", "Roche filonienne", "crystalline", "light", "quartz", "yes", "no", "no", "no", "none", "hydrothermal", "coarse"),
    _rock("Amphibolite", "Roche métamorphique", "foliated", "dark", "amphibole,feldspar", "yes", "no", "yes", "no", "none", "metamorphic", "medium"),
    _rock("Quartz-schiste", "Roche métamorphique", "foliated", "light", "quartz,mica", "yes", "no", "yes", "no", "none", "metamorphic", "medium"),
    _rock("Migmatite", "Roche métamorphique", "foliated", "light", "quartz,feldspar,mica", "yes", "no", "yes", "no", "none", "metamorphic", "coarse"),
    _rock("Éclogite", "Roche métamorphique", "crystalline", "dark", "garnet,pyroxene", "yes", "no", "no", "no", "none", "metamorphic", "medium"),
    _rock("Hornfels", "Roche métamorphique", "fine-grained", "dark", "mica,feldspar", "no", "no", "no", "no", "none", "metamorphic", "fine"),
    _rock("Skarn", "Roche métasomatique", "crystalline", "intermediate", "garnet,pyroxene,calcite", "yes", "no", "no", "no", "sometimes", "metasomatic", "medium"),
    _rock("Serpentinite", "Roche métamorphique", "crystalline", "green", "serpentine", "yes", "no", "no", "no", "none", "metamorphic", "fine"),
    _rock("Mylonite", "Roche métamorphique", "foliated", "intermediate", "quartz,feldspar,mica", "no", "no", "yes", "no", "none", "metamorphic", "fine"),
    _rock("Cataclasite", "Roche tectonique", "clastic-fine", "intermediate", "quartz,feldspar", "no", "no", "no", "no", "none", "tectonic", "fine", "no", "mixed", "angular"),
    _rock("Gneiss à grenat", "Roche métamorphique", "foliated", "intermediate", "quartz,feldspar,garnet", "yes", "no", "yes", "no", "none", "metamorphic", "coarse"),
    _rock("Marbre dolomitique", "Roche métamorphique", "crystalline", "light", "dolomite,calcite", "yes", "no", "no", "no", "strong", "metamorphic", "medium"),
    _rock("Amphibolite foliée", "Roche métamorphique", "foliated", "dark", "amphibole,feldspar", "yes", "no", "yes", "no", "none", "metamorphic", "medium"),
]


def expand_catalog(minerals, rocks):
    names = {m["name"] for m in minerals}
    minerals = minerals + [m for m in _EXTRA_MINERALS if m["name"] not in names]
    names = {r["name"] for r in rocks}
    rocks = rocks + [r for r in _EXTRA_ROCKS if r["name"] not in names]
    return minerals, rocks


# Additional observation questions. They are appended only if the original
# question catalog does not already contain the field.
def _add_questions():
    QUESTION_CATALOG["minerals"] += [
        ("transparency", "Quelle est la transparence ?", "La lumière traverse-t-elle l'échantillon ?", [
            ("transparent", "Transparent", "La lumière traverse nettement", None),
            ("translucent", "Translucide", "La lumière passe mais les détails sont diffus", None),
            ("opaque", "Opaque", "La lumière ne traverse pas", None),
        ]),
        ("density", "Quelle est la densité apparente ?", "Comparez le poids dans la main à un fragment de taille similaire.", [
            ("light", "Léger", "Semble peu dense", None), ("medium", "Moyenne", "Poids intermédiaire", None), ("heavy", "Lourd", "Étonnamment lourd pour sa taille", None),
        ]),
        ("fracture", "Quelle est la cassure ?", "Observez une surface cassée, sans provoquer de cassure volontaire.", [
            ("conchoidal", "Conchoïdale", "Courbes en coquille", None), ("uneven", "Irrégulière", "Surface irrégulière", None), ("splintery", "Échardée", "Aspect fibreux ou en échardes", None), ("earthy", "Terreuse", "Aspect friable/terreux", None),
        ]),
        ("magneticStrength", "Quelle est l'intensité magnétique ?", "Si une observation magnétique a déjà été faite dans un cadre approprié.", [
            ("none", "Aucune", None, None), ("weak", "Faible", None, None), ("strong", "Forte", None, None),
        ]),
    ]
    QUESTION_CATALOG["rocks"] += [
        ("rockType", "Quel grand type de roche semble correspondre ?", "Utilisez les indices visibles et votre contexte géologique.", [
            ("igneous", "Magmatique", None, None), ("volcanic", "Volcanique / volcanoclastique", None, None),
            ("sedimentary", "Sédimentaire", None, None), ("metamorphic", "Métamorphique", None, None),
            ("metasomatic", "Métasomatique", None, None), ("hydrothermal", "Hydrothermale / filonienne", None, None), ("tectonic", "Tectonique", None, None),
        ]),
        ("grainSize", "Quelle est la taille dominante des grains ?", "Observez à l'œil nu ou avec une loupe.", [
            ("very-fine", "Très fine", None, None), ("fine", "Fine", None, None), ("medium", "Moyenne", None, None),
            ("coarse", "Grossière", None, None), ("very-coarse", "Très grossière", None, None),
        ]),
        ("vesicles", "Y a-t-il des vacuoles ?", "Des cavités laissées par des bulles, sans casser l'échantillon.", [
            ("yes", "Oui", None, None), ("no", "Non", None, None),
        ]),
        ("sorting", "Les grains sont-ils bien triés ?", "Comparez les tailles des grains ou clastes.", [
            ("well-sorted", "Bien triés", None, None), ("poorly-sorted", "Mal triés", None, None), ("mixed", "Mélangés", None, None),
        ]),
        ("rounding", "Quelle est la forme des grains ou clastes ?", "Arrondis ou anguleux, lorsque des clastes sont visibles.", [
            ("rounded", "Arrondis", None, None), ("subrounded", "Subarrondis", None, None), ("angular", "Anguleux", None, None), ("mixed", "Mixte", None, None),
        ]),
    ]

_add_questions()

# Extend answer choices so the larger catalog remains selectable in the same UI.
def _extend_choice(field, kind, values):
    for i, (qfield, title, help_text, options) in enumerate(QUESTION_CATALOG[kind]):
        if qfield != field:
            continue
        existing = {o[0] for o in options}
        additions = [(v, label, None, None) for v, label in values if v not in existing]
        QUESTION_CATALOG[kind][i] = (qfield, title, help_text, options + additions)
        break

_extend_choice("luster", "minerals", [("adamantine", "Adamantin"), ("resinous", "Résineux")])
_extend_choice("crystalHabit", "minerals", [
    ("bladed", "En lames"), ("fibrous", "Fibreux"), ("tabular", "Tabulaire"),
    ("acicular", "Aciculaire"), ("rhombohedral", "Rhomboédrique"),
    ("octahedral", "Octaédrique"), ("wedge", "En coin"), ("tetrahedral", "Tétraédrique"),
    ("wedge", "En coin"),
])
_extend_choice("visibleMinerals", "rocks", [
    ("serpentine", "Serpentine"), ("clay", "Minéraux argileux"), ("apatite", "Apatite"),
    ("dolomite", "Dolomite"), ("halite", "Halite"), ("pyroxene", "Pyroxène"),
])
_extend_choice("dominantColor", "rocks", [("green", "Verte")])

# More non-destructive observation questions for the expanded questionnaire.
_extend_choice("luster", "minerals", [("submetallic", "Submétallique")])
QUESTION_CATALOG["minerals"] += [
    ("surface", "Quel est l'aspect de la surface ?", "Observez une surface naturelle ou une cassure déjà présente.", [
        ("smooth", "Lisse", None, None), ("rough", "Rugueuse", None, None), ("fibrous", "Fibreuse", None, None), ("earthy", "Terreuse", None, None),
    ]),
    ("habitVisibility", "Les cristaux individuels sont-ils bien définis ?", "Regardez si des faces cristallines nettes sont visibles.", [
        ("well-defined", "Bien définis", None, None), ("partly-defined", "Partiellement définis", None, None), ("not-visible", "Non visibles", None, None),
    ]),
    ("cleavageQuality", "Le clivage est-il net ?", "Seulement si des plans de clivage sont déjà visibles.", [
        ("perfect", "Très net", None, None), ("good", "Net", None, None), ("poor", "Peu net", None, None), ("none", "Absent", None, None),
    ]),
    ("surfaceAlteration", "La surface montre-t-elle une altération visible ?", "Comparez une surface fraîche et une surface altérée si elles sont déjà disponibles.", [
        ("none", "Peu ou pas d'altération", None, None), ("moderate", "Altération visible", None, None), ("strong", "Altération importante", None, None),
    ]),
]
QUESTION_CATALOG["rocks"] += [
    ("matrix", "Y a-t-il une matrice fine autour des grains ou clastes ?", "Observez si des éléments plus fins entourent les éléments principaux.", [
        ("yes", "Oui", None, None), ("no", "Non", None, None),
    ]),
    ("cement", "Quel ciment semble relier les grains ?", "Lorsque le ciment est visible ou déjà connu.", [
        ("carbonate", "Carbonaté", None, None), ("siliceous", "Siliceux", None, None), ("clayey", "Argileux", None, None), ("none", "Non visible", None, None),
    ]),
    ("fabric", "Comment les éléments sont-ils organisés ?", "Regardez l'orientation ou l'organisation générale de la roche.", [
        ("massive", "Massive", None, None), ("aligned", "Alignés", None, None), ("layered", "En couches", None, None), ("random", "Sans orientation nette", None, None),
    ]),
    ("weathering", "Quel est le degré d'altération visible ?", "Évaluez seulement l'aspect de surface observé.", [
        ("low", "Faible", None, None), ("moderate", "Modérée", None, None), ("high", "Forte", None, None),
    ]),
]
